version: '3.8'

services:
  cashi-fees-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: cashi-fees-service
    ports:
      - "8181:8181" # Expose port 8181 to host
      - "9080:9080" # Expose port 9080 for internal communication
    networks:
      - restate-network

    environment:
      - RESTATE_CLIENT_ENDPOINT=http://restate-dev:8080

  restate-server:
    image: docker.restate.dev/restatedev/restate:latest
    container_name: restate-dev
    ports:
      - "8080:8080"  # Expose port 8080 for workflow API
      - "9070:9070"  # Expose port 9070 for service registration
      - "9071:9071"  # Expose port 9071 (if needed for other services)
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Add the host gateway as the internal host
    restart: always
    networks:
      - restate-network

  deploy-service:
    image: curlimages/curl:latest
    container_name: deploy_service
    command: ["/bin/sh", "-c", "until curl -s http://cashi-fees-service:9080/health; do echo 'Waiting for cashi-fees-service...'; sleep 2; done && \
      curl -X POST http://restate-dev:9070/deployments \
      -H 'Content-Type: application/json' \
      -d '{\"uri\": \"http://cashi-fees-service:9080\"}'"]
    networks:
      - restate-network
    depends_on:
      - cashi-fees-service
      - restate-server

networks:
  restate-network:
    driver: bridge
