version: '3.8'

services:
  restate-server:
    image: docker.restate.dev/restatedev/restate:latest
    container_name: restate_dev
    ports:
      - "8080:8080"  # Expose port 8080 for workflow API
      - "9070:9070"  # Expose port 9070 (you can check if this port is needed for other services)
      - "9071:9071"  # Expose port 9071 (you can check if this port is needed for other services)
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Add the host gateway as the internal host
    restart: always
    networks:
      - restate-network

networks:
  restate-network:
    driver: bridge
